In [6]:
import numpy as np
a=np.random.randint(1, 100, size=(3,4))

print(np.ndarray.tolist(a))

[[57, 9, 27, 33], [67, 92, 50, 18], [18, 26, 93, 49]]


In [50]:
import numpy as np
a=np.random.randint(1, 100, size=(3,3))
print(a)
print(np.trace(a))

[[82 28 83]
 [38 17 24]
 [27 14 75]]
174


In [63]:
import numpy as np
a=np.random.randint(1, 100, size=(3,3))
print(a)
b=0
c=np.ndarray.tolist(a)
for i in range(len(c)):
    b=b+a[i,i]
print(b)


[[91 85 93]
 [58 50 58]
 [10 84 40]]
181


In [29]:
import numpy as np
a=np.random.randint(1, 50, size=(3,4))

print("original array :")
print(a)
print("values that are bigger than 5 :", a[a>5])

original array :
[[18 43 19 18]
 [ 4 48 33  7]
 [37 40 34 49]]
values that are bigger than 5 : [18 43 19 18 48 33  7 37 40 34 49]


In [31]:
import numpy as np
a=np.random.randint(1, 50, size=(3,4))
b=np.random.randint(1, 50, size=(3,4))
c=a+b
print("the first array is :")
print(a)
print("the second array is :")
print(b)
print("if we sum the values of those arrays, we have :")
print(c)

the first array is :
[[ 6  4 27 14]
 [12 38 49 22]
 [46 39 15 25]]
the second array is :
[[ 6 20 13 19]
 [43 29 32 42]
 [39 45 11 27]]
if we sum the values of those arrays, we have :
[[12 24 40 33]
 [55 67 81 64]
 [85 84 26 52]]


In [49]:
import numpy as np
a=np.random.randint(1, 10, size=(3,3))
print("the array is :")
print(a)
b=np.mean(a, axis=1)
print("the means of the raws of this array are :")
print(b)
c=np.ndarray.tolist(b)
d=c[0]
for i in range(1, len(c)):
    d=d-c[i]
print("the subtract of those mean is", d)

the array is :
[[4 6 3]
 [6 9 3]
 [4 1 7]]
the means of the raws of this array are :
[4.33333333 6.         4.        ]
the subtract of those mean is -5.666666666666667
